#!/bin/bash

echo "Put the operation down below"

read oper var1 var2

case $oper in
	sum)
	let res=$(($var1+$var2))
	echo $res
	;;
	sub)
	let res=$(($var1-$var2))
	echo $res
	;;
	mul)
	let res=$(($var1*$var2))
	echo $res
	;;
	div)  	if [[ $var2 -ne 0 ]]; then
		let res=$(($var1/$var2))
		echo $res
		 else
		echo "You can't divide by 0"
		fi
	;;
	*)
	echo "Something went wrong"
	;;
esac
