#!/bin/bash

case $1 in
	sum)
	let res=$(($2+$3))
	echo $res
	;;
	sub)
	let res=$(($2-$3))
	echo $res
	;;
	mul)
	let res=$(($2*$3))
	echo $res
	;;
	div)  	if [[ $3 -ne 0 ]]; then
		let res=$(($2/$3))
		echo $res
		 else
		echo "You can't divide by 0"
		fi
	;;
	*)
	echo "Something went wrong"
	;;
esac
