#!/bin/bash

excp() {
	echo "Error: $1" >> /dev/stderr
	exit 0
}

wrong_type_argument() {
	echo "Wrong type argument: $1" >> /dev/stderr
	exit 0
}

wrong_arguments_amount() {
	echo "Error: wrong amount of arguments" >> /dev/stderr
	exit 0
}
