#!/bin/bash

log() {
	log_file="/var/log/anaconda/X.log"
	Warning=$(cat $log_file | awk '/\[/ && /WW/') >> /dev/null	
	Information=$(cat $log_file | awk '/\[/ && /II/') >> /dev/null
	echo -e "${Warning//"(WW)"/"\033[93m Warning: \033[0m"}"
	echo -e "${Information//"(II)"/"\033[34m Information: \033[0m"}"
}
