#!/bin/bash

source calc
source search
source reverse
source strlen
source exiit
source hellp
source log
source exceptions
source interactive

case "$1" in
	"calc")
	[[ $# -ne 4 ]] && wrong_arguments_amount
	calc $2 $3 $4
	;;
	"search")
	[[ $# -ne 3 ]] && wrong_arguments_amount
	search $2 $3
	;;
	"reverse")
	[[ $# -ne 3 ]] && wrong_arguments_amount
	reverse $2 $3
	;;
	"strlen")
	[[ $# -ne 2 ]] && wrong_arguments_amount
	strlen $2
	;;
	"log")
	[[ $# -ne 1 ]] && wrong_arguments_amount
	log
	;;
	"exit")
	[[ $# -eq 1 ]] && exit 0
	[[ $# > 2 ]] && wrong_arguments_amount
	exiit $2
	;;
	"help")
	[[ $# -ne 1 ]] && wrong_arguments_amount
	hellp
	;;
	"interactive")
	[[ $# -ne 1 ]] && wrong_arguments_amount
	interactive
	;;
	*)
	excp "This command doesn't exist"
	;;
esac
