#!/bin/bash

source exceptions

reverse () {
if [[ -f $1 ]] && [[ -f $2 ]]
then rev $1 > n
tac n > $2
rm n
else if [[ ! -r $1 ]] && [[ ! -f $1 ]] 
	then excp "Cannot open the file or it doesn't exist"
	else excp "Cannot write the file"
	fi
fi
}
